# analysis_options.yaml

include:
  - package:very_good_analysis/analysis_options.yaml
  - package:bloc_lint/recommended.yaml

analyzer:
  exclude:
    - lib/l10n/gen/*
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    # تم إرجاع هذه القاعدة لأن استيراد حزم غير مسجلة في الـ pubspec يؤدي لانهيار المشروع عند البناء (Build Failure) في البيئات الأخرى.
    depend_on_referenced_packages: error
    
    # تم تركها مستثناة بناءً على رغبتك لتسهيل التعامل مع تحديثات Flutter UI المؤقتة.
    deprecated_member_use: ignore

linter:
  rules:
    avoid_dynamic_calls: true
    eol_at_end_of_file: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    directives_ordering: false
    avoid_redundant_argument_values: false
    omit_local_variable_types: false
    unnecessary_raw_strings: false
    no_literal_bool_comparisons: false
    avoid_catches_without_on_clauses: false
    avoid_types_on_closure_parameters: false
    always_put_required_named_parameters_first: false
    sort_constructors_first: false
    always_use_package_imports: false
    prefer_int_literals: false
    prefer_final_locals: false
    prefer_single_quotes: false
    discarded_futures: false
    unawaited_futures: false
    curly_braces_in_flow_control_structures: false
    unnecessary_ignore: false
    use_build_context_synchronously: false
    inference_failure_on_function_invocation: false
    inference_failure_on_instance_creation: false
    avoid_positional_boolean_parameters: false
    # 🌟 إسكات المفتش للأشياء التي لا تؤثر على جودة التطبيق:
    inference_failure_on_function_return_type: false
    dead_code: false
    dead_null_aware_expression: false
    avoid_print: false
    avoid_slow_async_io: false
    unnecessary_null_checks: false
    unnecessary_non_null_assertion: false
    empty_catches: false
    noop_primitive_operations: false
    prefer_const_constructors: false